### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by garyo** [SIsilicon/Volume-Renderer#2]
Any chance you could release this under a more permissive license? As is, I don't think it can be used by any commercial closed-source game.

**Comment by SIsilicon** [comment]
What. The MIT license? Assuming that's what you mean. Before I sent another update it used to be Gplv3.

**Comment by SIsilicon** [comment]
*Looks back at LICENSE.md*
Woops! Forgot about that license.
It's fixed now. Same goes for the asset store. It hasn't been updated yet though.
